# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Sierra Valley' do
    pod 'Google/Analytics'
end

target 'Sierra ValleyTests' do
    pod 'Google/Analytics'
end

target 'Sierra ValleyUITests' do

end
